language: scala
sudo: required

services:
   - docker

scala:
   - 2.11.7
jdk:
   - oraclejdk8


cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

script:
  - sbt  ++$TRAVIS_SCALA_VERSION clean coverage test integration:test
  - sbt  ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt  ++$TRAVIS_SCALA_VERSION codacyCoverage


  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
