language: scala
sudo: true #use legacy travis infra which works better
scala:
   - 2.11.6
jdk:
   - oraclejdk8


cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

before_script:
  - mkdir -p $HOME/.sbt/launchers/0.13.8/
  - curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar

script: "sbt clean test"
